edition = "2024"
group_imports = "StdExternalCrate"
hard_tabs = false
imports_granularity = "Crate"
max_width = 120
reorder_imports = true
struct_lit_single_line = false
tab_spaces = 2
use_small_heuristics = "Off"